# Generated by Django 2.2.24 on 2022-12-09 14:32

from django.db import migrations
from property.models import Owner


def transfer(apps, Flat):

    Flat = apps.get_model('property', 'Flat')

    for flat in Flat.objects.all().iterator():

        Owner.objects.get_or_create(
            name=flat.owner,
            phonenumber=flat.phonenumber,
            pure_phone=flat.pure_phone,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_auto_20230127_2011'),
    ]

    operations = [
        migrations.RunPython(transfer)
    ]

