# Generated by Django 2.2.24 on 2022-12-06 15:58

from django.db import migrations


def change_building_status(apps, Flat):
    Flat = apps.get_model('property', 'Flat')

    for flat in Flat.objects.all():

        if 2014 < flat.construction_year:
            flat.new_building = True
            flat.save()
            #Flat.objects.update_or_create(owner=flat.owner,
            #                            price=flat.price,
            #                            new_building=True,
            #                            rooms_number=flat.rooms_number,
            #                            active=flat.active)
        else:
            flat.new_building = False
            flat.save()

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(change_building_status),
    ]
