# Generated by Django 2.2.24 on 2022-12-21 16:05

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_auto_20190829_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='_flat_liked_by_+', to='property.Flat', verbose_name='лайки'),
        ),
        migrations.AddField(
            model_name='flat',
            name='new_building',
            field=models.BooleanField(choices=[(True, 'Новостройка'), (False, 'Cтарое здание')], db_index=True, default=False, null=True, verbose_name='Статус постройки здания'),
        ),
        migrations.AddField(
            model_name='flat',
            name='owner_pure_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region='RU', verbose_name='Нормализованный номер владельца'),
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=200, verbose_name='ФИО владельца')),
                ('owner_pure_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region='RU', verbose_name='Нормализованный номер владельца')),
                ('owners_phonenumber', models.CharField(max_length=20, verbose_name='Номер владельца')),
                ('apartment_owner', models.ManyToManyField(blank=True, related_name='owners', to='property.Flat', verbose_name='Квартир(а\\ы) в собственности')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('who', models.CharField(max_length=200, verbose_name='Кто жаловался')),
                ('text', models.TextField(verbose_name='Текст жалобы')),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='property.Flat', verbose_name='Адрес')),
            ],
        ),
    ]
