# Generated by Django 2.2.24 on 2022-12-06 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_flat_new_building'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='new_building',
            field=models.BooleanField(choices=[(True, 'Новостройка'), (False, 'Cтарое здание')], default='default', verbose_name='Статус постройки здания'),
            preserve_default=False,
        ),
    ]
