# Generated by Django 2.2.24 on 2022-12-06 15:58

from django.db import migrations


def change_building_status(apps, Flat):
    Flat = apps.get_model('property', 'Flat')

    for flat in Flat.objects.filter(construction_year__year=2014):

        if 2014 < flat.construction_year:
            flat.new_building = True
        else:
            flat.new_building = False

        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_auto_20221221_1905'),
    ]

    operations = [
        migrations.RunPython(change_building_status),
    ]
