# Generated by Django 2.2.24 on 2022-12-09 14:32

from django.db import migrations
from property.models import Owner


def transfer(apps, Flat):

    Flat = apps.get_model('property', 'Flat')

    for falt in Flat.objects.all().iterator():

        Owner.objects.get_or_create(
            name=falt.owner,
            phone=falt.owner_pure_phone,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_auto_20230105_0850'),
    ]

    operations = [
        migrations.RunPython(transfer)
    ]
