# Generated by Django 2.2.24 on 2022-12-09 14:32

from django.db import migrations


def move_backwards(apps, Owner):
    Owner = apps.get_model('property', 'Owner')

    for owner in Owner.objects.all().iterator():
        owner.apartment.clear()


def fill_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')

    for owner in Owner.objects.all().iterator():
        owner.apartment.set(Flat.objects.filter(owner=owner.name))


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_auto_20230127_1641'),
    ]

    operations = [
        migrations.RunPython(fill_owners)
    ]
