# Generated by Django 2.2.24 on 2023-01-27 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_auto_20230127_2022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='name',
            new_name='owner',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='phonenumber',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='pure_phone',
        ),
        migrations.AlterField(
            model_name='flat',
            name='new_building',
            field=models.BooleanField(choices=[('NEW_BUILDING', 'Новостройка'), ('OLD_BUILDING', 'Cтарое здание'), ('UNKNOWN', 'Неизвестно')], db_index=True, default='UNKNOWN', null=True, verbose_name='Статус постройки здания'),
        ),
    ]
