# Generated by Django 2.2.24 on 2023-01-31 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_auto_20230127_2041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='apartment',
            new_name='apartments',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='owner',
            new_name='name',
        ),
    ]
