# Generated by Django 2.2.24 on 2022-12-29 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_auto_20221221_1917'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserComplaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст жалобы')),
            ],
        ),
        migrations.RenameField(
            model_name='flat',
            old_name='owners_phonenumber',
            new_name='phonenumber',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='apartment_owner',
            new_name='apartment',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='owner_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='owner_pure_phone',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='liked_by',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='owner_pure_phone',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='owners_phonenumber',
        ),
        migrations.DeleteModel(
            name='Complaint',
        ),
        migrations.AddField(
            model_name='usercomplaint',
            name='apartment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='property.Flat', verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='usercomplaint',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_apartments', to='property.Flat', verbose_name='лайки'),
        ),
        migrations.AddField(
            model_name='usercomplaint',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='property.Owner', verbose_name='Кто жаловался'),
        ),
    ]
