# Generated by Django 2.2.24 on 2023-07-12 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_auto_20230131_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='new_building',
            field=models.BooleanField(choices=[(True, 'Новостройка'), (False, 'Cтарое здание')], db_index=True, default='UNKNOWN', null=True, verbose_name='Статус постройки здания'),
        ),
    ]
