# Generated by Django 2.2.24 on 2022-12-07 14:47
import phonenumbers

from django.db import migrations


def normalization_number(apps, Flat):
    Flat = apps.get_model('property', 'Flat')
    print(3)
    for flat in Flat.objects.all():

        owners_phonenumber = flat.owners_phonenumber
        phone_number = phonenumbers.parse(owners_phonenumber, 'RU')
        flat.owner_pure_phone = phonenumbers.format_number(phone_number, phonenumbers.PhoneNumberFormat.E164)
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_auto_20221207_1747'),
    ]

    operations = [
        migrations.RunPython(normalization_number)
    ]
