# Generated by Django 2.2.24 on 2022-12-09 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_owner'),
    ]

    operations = [
    ]
