# Generated by Django 2.2.24 on 2022-12-09 14:32

from django.db import migrations


def fill_owners(apps, schema_editor):

    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')

    


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0019_auto_20221218_1523'),
    ]

    operations = [
        migrations.RunPython(fill_owners)
    ]
