# Generated by Django 2.2.24 on 2022-12-20 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0020_auto_20221218_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('who', models.CharField(max_length=200, verbose_name='Кто жаловался')),
                ('complaint', models.TextField(verbose_name='Текст жалобы')),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='property.Flat', verbose_name='Адрес')),
            ],
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='name',
            new_name='owner_name',
        ),
        migrations.AlterField(
            model_name='owner',
            name='apartment_owner',
            field=models.ManyToManyField(blank=True, related_name='owners', to='property.Flat', verbose_name='Квартир(а\\ы) в собственности'),
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
