# Generated by Django 2.2.24 on 2022-12-09 14:32

from django.db import migrations


def fill_owners(apps, schema_editor):

    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')

    for owner in Owner.objects.all():
        owner.apartment_owner.set(Flat.objects.filter(owner=owner.owner_name))
        owner.apartment_owner.clear()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0022_auto_20221220_1521'),
    ]

    operations = [
        migrations.RunPython(fill_owners)
    ]
